//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answerID { get; set; }
        public string answerText { get; set; }
        public Nullable<System.DateTime> answerDate { get; set; }
        public Nullable<int> questionID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> approveUserID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
