//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentID { get; set; }
        public string commentText { get; set; }
        public string positive { get; set; }
        public string negative { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<int> approveUserID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
