//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.Faqs = new HashSet<Faq>();
            this.Socials = new HashSet<Social>();
        }
    
        public int contentID { get; set; }
        public string employeText { get; set; }
        public string aboutUs { get; set; }
        public string title { get; set; }
        public string whyUs { get; set; }
        public string shortDescription { get; set; }
        public string policy { get; set; }
        public string rules { get; set; }
        public string adress { get; set; }
        public string phones { get; set; }
        public string email { get; set; }
        public string contactUs { get; set; }
        public string hireInfo { get; set; }
        public string presentationInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faq> Faqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Social> Socials { get; set; }
    }
}
