//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCost
    {
        public int deliveryCostID { get; set; }
        public Nullable<int> fromCityID { get; set; }
        public Nullable<int> toCityID { get; set; }
        public Nullable<int> cost { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
