//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuaranteeState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuaranteeState()
        {
            this.GuaranteeProducts = new HashSet<GuaranteeProduct>();
            this.GuaranteeProductStates = new HashSet<GuaranteeProductState>();
        }
    
        public int guaranteeStateID { get; set; }
        public string stateName { get; set; }
        public Nullable<int> usergroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuaranteeProduct> GuaranteeProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuaranteeProductState> GuaranteeProductStates { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
