//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuaranteeProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuaranteeProduct()
        {
            this.GuaranteeProductExtraItems = new HashSet<GuaranteeProductExtraItem>();
            this.GuaranteeProductStates = new HashSet<GuaranteeProductState>();
        }
    
        public int guaranteeProductID { get; set; }
        public string productName { get; set; }
        public string model { get; set; }
        public string serialNumber { get; set; }
        public Nullable<int> guaranteeStateID { get; set; }
        public Nullable<System.DateTime> buyTime { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public Nullable<System.DateTime> doneDate { get; set; }
        public Nullable<System.DateTime> customerDeliveryDate { get; set; }
        public Nullable<int> guaranteeServiceCompanyID { get; set; }
        public Nullable<int> guaranteeCustomerID { get; set; }
        public Nullable<int> userID { get; set; }
        public string description { get; set; }
        public string result { get; set; }
        public Nullable<System.DateTime> confirmDate { get; set; }
        public string customerOpinion { get; set; }
        public string repairManOpinion { get; set; }
        public string physicalProblems { get; set; }
        public Nullable<int> amvalNumber { get; set; }
        public Nullable<int> trackingCode { get; set; }
        public string include { get; set; }
    
        public virtual GuaranteeCustomer GuaranteeCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuaranteeProductExtraItem> GuaranteeProductExtraItems { get; set; }
        public virtual GuaranteeServiceCompany GuaranteeServiceCompany { get; set; }
        public virtual GuaranteeState GuaranteeState { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuaranteeProductState> GuaranteeProductStates { get; set; }
    }
}
