//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuaranteeProductState
    {
        public int guaranteeProductStateID { get; set; }
        public int guaranteeStateID { get; set; }
        public int guaranteeProductID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> userID { get; set; }
        public string promt { get; set; }
        public string confirm { get; set; }
    
        public virtual GuaranteeProduct GuaranteeProduct { get; set; }
        public virtual GuaranteeState GuaranteeState { get; set; }
        public virtual User User { get; set; }
    }
}
