//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuaranteeProductExtraItem
    {
        public int guaranteeProductExtraItemID { get; set; }
        public int guaranteeExtraItemID { get; set; }
        public int guaranteeProductID { get; set; }
    
        public virtual GuaranteeExtraItem GuaranteeExtraItem { get; set; }
        public virtual GuaranteeProduct GuaranteeProduct { get; set; }
    }
}
