//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class list
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string title { get; set; }
        public string discount { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string description { get; set; }
    }
}
