//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Rizkaran_SiteEntities : DbContext
    {
        public Rizkaran_SiteEntities()
            : base("name=Rizkaran_SiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AccessStore> AccessStores { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<AttribteValueType> AttribteValueTypes { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CKEditorImageUpload> CKEditorImageUploads { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<DeliveryCost> DeliveryCosts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceType> InvoiceTypes { get; set; }
        public virtual DbSet<list> lists { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<OrderState> OrderStates { get; set; }
        public virtual DbSet<Orde> Ordes { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<ProductAttribute> ProductAttributes { get; set; }
        public virtual DbSet<ProductAttributeTemplateGroup> ProductAttributeTemplateGroups { get; set; }
        public virtual DbSet<ProductAttributeTemplate> ProductAttributeTemplates { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductColorAssinment> ProductColorAssinments { get; set; }
        public virtual DbSet<ProductColor> ProductColors { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<ProductKeyword> ProductKeywords { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductState> ProductStates { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ResponsibleStore> ResponsibleStores { get; set; }
        public virtual DbSet<Seo> Seos { get; set; }
        public virtual DbSet<ShopCarousel> ShopCarousels { get; set; }
        public virtual DbSet<Social> Socials { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTracking> UserTrackings { get; set; }
        public virtual DbSet<GuaranteeCustomer> GuaranteeCustomers { get; set; }
        public virtual DbSet<GuaranteeExtraItem> GuaranteeExtraItems { get; set; }
        public virtual DbSet<GuaranteeProductExtraItem> GuaranteeProductExtraItems { get; set; }
        public virtual DbSet<GuaranteeProduct> GuaranteeProducts { get; set; }
        public virtual DbSet<GuaranteeProductState> GuaranteeProductStates { get; set; }
        public virtual DbSet<GuaranteeServiceCompany> GuaranteeServiceCompanies { get; set; }
        public virtual DbSet<GuaranteeState> GuaranteeStates { get; set; }
    }
}
