//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        public long productAttributeID { get; set; }
        public Nullable<long> productAtrributeTemplateID { get; set; }
        public string value { get; set; }
        public Nullable<int> productID { get; set; }
    
        public virtual ProductAttributeTemplate ProductAttributeTemplate { get; set; }
        public virtual Product Product { get; set; }
    }
}
