//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttributeTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductAttributeTemplate()
        {
            this.ProductAttributes = new HashSet<ProductAttribute>();
        }
    
        public long productAtrributeTemplateID { get; set; }
        public string name { get; set; }
        public Nullable<byte> attributeValueTypeID { get; set; }
        public Nullable<int> unitID { get; set; }
        public Nullable<bool> searchable { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> ProductAttributeTemplateGroupID { get; set; }
    
        public virtual AttribteValueType AttribteValueType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttribute> ProductAttributes { get; set; }
        public virtual ProductAttributeTemplateGroup ProductAttributeTemplateGroup { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
