//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsibleStore
    {
        public int responsibleStoreID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> storeID { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
