//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seo
    {
        public int seoID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> brandID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Product Product { get; set; }
    }
}
