//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social
    {
        public int socialID { get; set; }
        public string type { get; set; }
        public string socialIcon { get; set; }
        public string url { get; set; }
        public Nullable<int> contentID { get; set; }
        public Nullable<int> employeID { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
